# Generated by Django 4.2 on 2023-04-18 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
